//
//  SearchCityInteractor.swift
//  CleanSwiftTemplates
//
//  Created by Adria Ros Saez on 1/10/18.
//  Copyright (c) 2018 adriaros. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchCityBusinessLogic
{
  func doSomething(request: SearchCity.Something.Request)
}

protocol SearchCityDataStore
{
  //var name: String { get set }
}

class SearchCityInteractor: SearchCityBusinessLogic, SearchCityDataStore
{
  var presenter: SearchCityPresentationLogic?
  var worker: SearchCityWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: SearchCity.Something.Request)
  {
    worker = SearchCityWorker()
    worker?.doSomeWork()
    
    let response = SearchCity.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
