//
//  ViewWeatherPresenter.swift
//  CleanSwiftTemplates
//
//  Created by Adria Ros Saez on 1/10/18.
//  Copyright (c) 2018 adriaros. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ViewWeatherPresentationLogic
{
  func presentSomething(response: ViewWeather.Something.Response)
}

class ViewWeatherPresenter: ViewWeatherPresentationLogic
{
  weak var viewController: ViewWeatherDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: ViewWeather.Something.Response)
  {
    let viewModel = ViewWeather.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
